// src/app/visitor/locations/detail/detail.component.ts
import { CommonModule, NgFor, NgIf } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { LocationService } from '../../../services/location.service';

@Component({
  selector: 'app-location-detail',
  standalone: true,
  imports: [CommonModule, NgIf, NgFor, RouterModule],
  templateUrl: './detail.component.html'
})
export class LocationDetailComponent implements OnInit {
  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private locationService: LocationService
  ) {}

  loading: boolean = true;
  error: string | null = null;
  locationId: string | null = null;
  location: any = null;
  isMenuOpen: boolean = false;
  currentImageIndex: number = 0;
  currentYear: number = new Date().getFullYear();

  async ngOnInit(): Promise<void> {
    try {
      this.locationId = this.route.snapshot.paramMap.get('id');
      if (!this.locationId) {
        this.error = 'Location ID not found';
        this.loading = false;
        return;
      }

      const rows = await this.locationService.getLocationInfo(this.locationId);
      this.location = Array.isArray(rows) && rows.length > 0 ? rows[0] : null;
      if (!this.location) {
        this.error = 'Location not found';
      }
    } catch (err: any) {
      this.error = err?.message || 'Failed to load location';
    } finally {
      this.loading = false;
    }
  }

  backToList(): void {
    this.router.navigate(['../'], { relativeTo: this.route });
  }

  toggleMenu(): void {
    this.isMenuOpen = !this.isMenuOpen;
  }

  get galleryImages(): { url: string }[] {
    const imgs = Array.isArray(this.location?.images) ? this.location.images : [];
    return imgs.map((i: any) => ({ url: i?.url || '' })).filter((x: any) => !!x.url);
  }

  showPrev(): void {
    const n = this.galleryImages.length;
    if (n === 0) return;
    this.currentImageIndex = (this.currentImageIndex - 1 + n) % n;
  }

  showNext(): void {
    const n = this.galleryImages.length;
    if (n === 0) return;
    this.currentImageIndex = (this.currentImageIndex + 1) % n;
  }

  goArtistLogin(): void {
    this.router.navigate(['/artistspace']);
  }
}

<div class="bg-cream min-h-screen">
  <div *ngIf="loading" class="min-h-[60vh] flex items-center justify-center">
    <div class="text-center">
      <h1 class="text-2xl font-bold text-gray-900 mb-4">Loading venue...</h1>
    </div>
  </div>

  <div *ngIf="(error || !location) && !loading" class="min-h-[60vh] flex items-center justify-center">
    <div class="text-center">
      <h1 class="text-2xl font-bold text-gray-900 mb-4">{{ error || 'Venue Not Found' }}</h1>
      <button class="bg-pont-rust hover:bg-pont-rust/90 text-white px-4 py-2 rounded" (click)="backToList()">
        <i class="fas fa-arrow-left mr-2"></i>
        Back to Locations
      </button>
    </div>
  </div>

  <div *ngIf="location && !loading" class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
    <div class="flex justify-between items-center mb-8">
      <div>
        <h1 class="text-4xl lg:text-5xl font-extrabold tracking-tight text-gray-800">{{ location.name }}</h1>
        <div class="flex items-center gap-4 mt-2 text-gray-600">
          <div class="flex items-center space-x-2">
            <i class="fa-solid fa-location-dot w-5 h-5"></i>
            <span class="font-semibold">{{ location.address }} {{ location.zip }}</span>
          </div>
        </div>
      </div>
      <button class="border bg-white/80 backdrop-blur-sm px-4 py-2 rounded" (click)="backToList()">
        <i class="fas fa-arrow-left mr-2 w-4 h-4"></i>
        Back to all locations
      </button>
    </div>

    <div class="grid md:grid-cols-3 gap-8 lg:gap-12">
      <!-- Left Column (Carousel) -->
      <div class="md:col-span-2">
        <div class="rounded-2xl shadow-2xl overflow-hidden relative">
          <ng-container *ngIf="galleryImages.length > 0; else carouselPlaceholder">
            <div class="aspect-video relative">
              <img [src]="galleryImages[currentImageIndex].url" [alt]="location.name" class="w-full h-full object-cover" />
            </div>
            <button class="absolute left-4 top-1/2 -translate-y-1/2 bg-white/80 hover:bg-white text-gray-700 rounded-full w-10 h-10 flex items-center justify-center shadow" (click)="showPrev()">
              <i class="fas fa-chevron-left"></i>
            </button>
            <button class="absolute right-4 top-1/2 -translate-y-1/2 bg-white/80 hover:bg-white text-gray-700 rounded-full w-10 h-10 flex items-center justify-center shadow" (click)="showNext()">
              <i class="fas fa-chevron-right"></i>
            </button>
          </ng-container>
          <ng-template #carouselPlaceholder>
            <div class="aspect-video relative">
              <img src="/assets/images/logo/logo.jpg" alt="Venue placeholder" class="w-full h-full object-cover" />
            </div>
          </ng-template>
        </div>
      </div>

      <!-- Right Column (Host Info + Map) -->
      <div class="space-y-6">

        <div class="shadow-lg rounded-2xl border-2 border-pont-green/20 bg-white">
          <div class="p-5 border-b">
            <h2 class="text-2xl font-bold text-pont-green flex items-center">
     <i class="fa-solid fa-star-of-life mr-3"></i>
              Host Information
            </h2>
          </div>
          <div class="p-5 space-y-4">
            <div class="flex items-center space-x-4">
              <img src="../../../../assets/images/profile/user-b.png" alt="Host" class="w-16 h-16 rounded-full border-2 border-pont-light-green" />
              <div>
                <p class="font-bold text-lg text-gray-800">Pontangler</p>
                <p class="text-sm text-gray-500">
                  Hosting since {{ (location.created_on | date:'yyyy') || currentYear }}
                </p>
              </div>
            </div>
          </div>
        </div>

        <div class="shadow-lg rounded-2xl border-2 border-pont-green/20 bg-white">
          <div class="p-5 border-b">
            <h2 class="text-2xl font-bold text-pont-green flex items-center">
              <i class="fa-solid fa-address-book mr-3"></i>
              Contact
            </h2>
          </div>
          <div class="p-5 space-y-3">
            <div *ngIf="location.phone" class="flex items-center space-x-3 text-gray-700">
              <i class="fa-solid fa-phone text-pont-green"></i>
              <a class="hover:underline" [href]="'tel:' + location.phone">{{ location.phone }}</a>
            </div>
            <div *ngIf="location.email" class="flex items-center space-x-3 text-gray-700">
              <i class="fa-solid fa-envelope text-pont-green"></i>
              <a class="hover:underline" [href]="'mailto:' + location.email">{{ location.email }}</a>
            </div>
            <div *ngIf="location.website" class="flex items-center space-x-3 text-gray-700">
              <i class="fa-solid fa-globe text-pont-green"></i>
              <a class="hover:underline break-all" [href]="location.website?.startsWith('http') ? location.website : 'http://' + location.website" target="_blank" rel="noopener">
                {{ location.website }}
              </a>
            </div>
          </div>
        </div>


    

     
      </div>
    </div>

    <div class="my-12 h-px bg-gray-200"></div>

    <!-- Main Content Area -->
    <div class="grid md:grid-cols-3 gap-8 lg:gap-12">
      <div class="md:col-span-2 space-y-8">
        <div class="flex items-center gap-4">
          <span *ngIf="location.type || location.residence_type" class="bg-gradient-to-r from-pont-green to-green-500 text-white border-none text-md py-2 px-4 rounded-full">{{ location.type || location.residence_type }}</span>
          <div class="flex flex-wrap gap-2">
            <span class="bg-pont-green text-white border font-normal rounded-full px-3 py-1" *ngFor="let t of (location.types || [])">{{ t.name | titlecase }}</span>

            <span class="bg-pont-light-green/40 text-pont-green border border-pont-green/20 font-normal rounded-full px-3 py-1" *ngFor="let t of (location.specs || [])">{{ t.name | titlecase }}</span>
          </div>
        </div>

        <div>
          <h2 class="text-3xl font-bold text-gray-800 mb-4">About this space</h2>
          <p class="text-lg text-gray-600 leading-relaxed">{{ location.description }}</p>
        </div>

        <div *ngIf="(location.amenities || []).length > 0">
          <h2 class="text-3xl font-bold text-gray-800 mb-6">What this place offers</h2>
          <div class="grid grid-cols-2 gap-4">
            <div class="flex items-center space-x-3" *ngFor="let a of location.amenities">
              <i class="far fa-check-circle text-pont-green"></i>
              <span class="text-gray-700">{{ a.name }}</span>
            </div>
          </div>
        </div>
      </div>

      <div>
           <div class="shadow-lg rounded-2xl border-2 border-pont-green/20 bg-white">
          <div class="p-5 border-b"></div>
          <div class="p-5 space-y-2">
            <!-- Map placeholder -->
            <div class="w-full h-60 bg-gray-100 rounded-xl flex items-center justify-center text-gray-500">Map coming soon</div>
          </div>
        </div>


      </div>

      <!-- Sticky details card placeholder removed as in TSX it's commented out -->
    </div>
  </div>
</div>

// src/app/visitor/locations/detail/page.tsx
"use client"

import { useState, useEffect } from "react"
import { useParams } from "next/navigation"
import Image from "next/image"
import Link from "next/link"
import { locationService, type Location } from "@/lib/supabase"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel"
import {
  MapPin,
  Users,
  Star,
  ArrowLeft,
  CheckCircle,
  Sparkles,
  Menu,
  X,
  Calendar,
  Facebook,
  Instagram,
  Mail,
  Twitter,
} from "lucide-react"
import dynamic from 'next/dynamic';

const Map = dynamic(() => import('./map'), {
  ssr: false, // Must disable SSR for Leaflet
});

export default function VenueDetailPage() {
  const params = useParams()
  const venueId = Number.parseInt(params.id as string)
  const [venue, setVenue] = useState<Location | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [isMenuOpen, setIsMenuOpen] = useState(false)

  useEffect(() => {
    async function fetchVenue() {
      setLoading(true)
      setError(null)
      try {
        const data = await locationService.getLocationById(venueId)
        setVenue(data)
      } catch (err: any) {
        setError("Venue not found.")
        setVenue(null)
      }
      setLoading(false)
    }
    if (!isNaN(venueId)) {
      fetchVenue()
    }
  }, [venueId])

  const Header = () => {
    return (
      <header className="backdrop-blur-md py-4 px-4 border-b border-gray-100 shadow-sm sticky top-0 z-50 bg-cream">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center justify-between">
            {/* Logo Only */}
            <div className="flex items-center">
              <Link href="/">
                <Image
                  src="/logo.jpg"
                  alt="Pont Ar Gler Logo"
                  width={100}
                  height={100}
                  className="shadow-md absolute top-4"
                />
              </Link>
            </div>

            {/* Desktop Navigation */}
            <nav className="hidden md:flex items-center space-x-10">
              <Link
                href="/"
                className="text-gray-700 hover:text-pont-green transition-all duration-300 font-medium text-lg relative group"
              >
                Discover
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-pont-green transition-all duration-300 group-hover:w-full"></span>
              </Link>
              <Link
                href="/concerts"
                className="text-gray-700 hover:text-pont-green transition-all duration-300 font-medium text-lg relative group"
              >
                Events
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-pont-green transition-all duration-300 group-hover:w-full"></span>
              </Link>
              <Link
                href="/artists"
                className="text-gray-700 hover:text-pont-green font-medium text-lg relative group"
              >
                Artists
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-pont-green transition-all duration-300 group-hover:w-full"></span>
              </Link>
            
              <Link
                href="/venues"
                className="text-pont-green font-medium text-lg relative group"
              >
                Locations
                <span className="absolute -bottom-1 left-0 w-full h-0.5 bg-pont-green"></span>
              </Link>
              <Link
                href="/about"
                className="text-gray-700 hover:text-pont-green transition-all duration-300 font-medium text-lg relative group"
              >
                About
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-pont-green transition-all duration-300 group-hover:w-full"></span>
              </Link>
            </nav>

            {/* Artist Auth Buttons */}
            <div className="hidden md:flex items-center space-x-4">
              <Button
                onClick={() => router.push("/artist-login")}
                className="bg-gradient-to-r from-lime-600 to-lime-700 hover:from-pont-rust/90 hover:to-pont-rust text-white px-8 py-2.5 rounded-sm font-semibold shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105"
              >
                Artist Login
              </Button>
            </div>

            {/* Mobile Menu Button */}
            <button
              onClick={() => setIsMenuOpen(!isMenuOpen)}
              className="md:hidden p-2 text-gray-700 hover:text-pont-green transition-colors rounded-lg hover:bg-pont-green/5"
            >
              {isMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
            </button>
          </div>

          {/* Mobile Menu */}
          {isMenuOpen && (
            <div className="md:hidden mt-4">
              <nav className="flex flex-col space-y-4">
                <Link href="/" className="text-gray-700 hover:text-pont-green">
                  Discover
                </Link>
                <Link href="/concerts" className="text-gray-700 hover:text-pont-green">
                  Events
                </Link>
                <Link href="/artists" className="text-gray-700 hover:text-pont-green">
                  Artists
                </Link>
            
                <Link href="/venues" className="text-pont-green font-bold">
                  Locations
                </Link>
                <Link href="/about" className="text-gray-700 hover:text-pont-green">
                  About
                </Link>
                <Button className="bg-gradient-to-r from-lime-600 to-lime-700 hover:from-pont-rust/90 hover:to-pont-rust text-white">
                  Artist Login
                </Button>
              </nav>
            </div>
          )}
        </div>
      </header>
    )
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-cream flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900 mb-4">Loading venue...</h1>
        </div>
      </div>
    )
  }

  if (error || !venue) {
    return (
      <div className="min-h-screen bg-cream flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900 mb-4">
            {error || "Venue Not Found"}
          </h1>
          <Link href="/venues">
            <Button className="bg-pont-rust hover:bg-pont-rust/90 text-white">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Venues
            </Button>
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="bg-cream min-h-screen">
      <Header />
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="flex justify-between items-center mb-8">
            <div>
                <h1 className="text-4xl lg:text-5xl font-extrabold tracking-tight text-gray-800">
                  {venue.name}
                </h1>
                <div className="flex items-center gap-4 mt-2 text-gray-600">
                   
                    <div className="flex items-center space-x-2">
                        <MapPin className="w-5 h-5" />
                        <span className="font-semibold">{venue.address} {venue.postal_code}</span>
                    </div>
                </div>
            </div>
          <Link href="/venues">
            <Button variant="outline" className="bg-white/80 backdrop-blur-sm">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to all venues
            </Button>
          </Link>
        </div>

        <div className="grid md:grid-cols-3 gap-8 lg:gap-12">
          {/* Left Column (Carousel) */}
          <div className="md:col-span-2">
            <Carousel className="rounded-2xl shadow-2xl overflow-hidden">
              <CarouselContent>
                {venue.location_images && venue.location_images.length > 0 ? (
                  venue.location_images.map((img: any, index: number) => (
                    <CarouselItem key={index}>
                      <div className="aspect-video relative">
                        <Image
                          src={img.image_url}
                          alt={`${venue.name} image ${index + 1}`}
                          layout="fill"
                          objectFit="cover"
                        />
                      </div>
                    </CarouselItem>
                  ))
                ) : (
                  <CarouselItem>
                    <div className="aspect-video relative">
                      <Image
                        src="/venues/v1.png"
                        alt="Venue placeholder"
                        layout="fill"
                        objectFit="cover"
                      />
                    </div>
                  </CarouselItem>
                )}
              </CarouselContent>
              <CarouselPrevious className="ml-16" />
              <CarouselNext className="mr-16" />
            </Carousel>
          </div>

          {/* Right Column (Host Info) */}
          <div className="space-y-6">
            <Card className="shadow-lg rounded-2xl border-2 border-pont-green/20">
              <CardHeader>
                <CardTitle className="text-2xl font-bold text-pont-green flex items-center">
                  <Sparkles className="w-6 h-6 mr-3" />
                  Host Information
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center space-x-4">
                  <Image
                    src="/placeholder-user.jpg"
                    alt={venue.name}
                    width={64}
                    height={64}
                    className="rounded-full border-2 border-pont-light-green"
                  />
                  <div>
                    <p className="font-bold text-lg text-gray-800">Pontangler</p>
                    <p className="text-sm text-gray-500">
                      Hosting since {venue.hosted_since}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

{/* Right Column (Google Map) */}
            
            <Card className="shadow-lg p-0 rounded-2xl border-2 border-pont-green/20">
              <CardHeader>  
                
              </CardHeader>
              <CardContent className="space-y-2">
                {/* Google Map Embed */}
                      <Map lat={venue.latitude} lng={venue.longitude} /> {/* Replace with your coordinates */}

              </CardContent>
            </Card>
          </div>

          
        </div>

        <Separator className="my-12" />

        {/* Main Content Area */}
        <div className="grid md:grid-cols-3 gap-8 lg:gap-12">
          <div className="md:col-span-2 space-y-8">
            <div className="flex items-center gap-4">
                {(venue.type || venue.residence_type) && (
                  <Badge className="bg-gradient-to-r from-pont-green to-green-500 text-white border-none text-md py-2 px-4 rounded-full">
                    {venue.type || venue.residence_type}
                  </Badge>
                )}
                <div className="flex flex-wrap gap-2">
                {(venue.location_tags || []).map((tag: string) => (
                    <Badge key={tag} variant="secondary" className="bg-pont-light-green/40 text-pont-green border-pont-green/20 font-normal">
                    {tag}
                    </Badge>
                ))}
                </div>
            </div>
            {/* Description */}
            <div>
              <h2 className="text-3xl font-bold text-gray-800 mb-4">
                About this space
              </h2>
              <p className="text-lg text-gray-600 leading-relaxed">
                {venue.description}
              </p>
            </div>

            {(venue.place_offers || []).length > 0 && (
              <div>
                <h2 className="text-3xl font-bold text-gray-800 mb-6">
                  What this place offers
                </h2>
                <div className="grid grid-cols-2 gap-4">
                  {venue.place_offers.map((amenity: string) => (
                    <div key={amenity} className="flex items-center space-x-3">
                      <CheckCircle className="w-6 h-6 text-pont-green" />
                      <span className="text-gray-700">{amenity}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Sticky Details Card */}
          {/* <div className="md:sticky top-24 self-start">
             <Card className="shadow-lg rounded-2xl overflow-hidden">
                <CardHeader className="bg-gray-50">
                    <CardTitle className="text-2xl font-bold text-gray-800">
                        Venue Details
                    </CardTitle>
                </CardHeader>
                <CardContent className="p-6 space-y-4">
                    <div className="flex items-center justify-between">
                        <span className="font-semibold text-gray-600">Capacity</span>
                        <div className="flex items-center space-x-2">
                           <Users className="w-5 h-5 text-pont-green" />
                           <span className="font-bold text-lg">{venue.capacity} guests</span>
                        </div>
                    </div>
                     <div className="text-center pt-4 border-t mt-4">
                        <p className="text-3xl font-extrabold text-gray-900">${venue.price}</p>
                        <p className="text-sm text-gray-500">per event</p>
                     </div>
                </CardContent>
                <CardFooter className="p-3">
                     <Button size="lg" className="w-full h-12 text-lg bg-pont-green hover:bg-pont-green/90 rounded-xl shadow-lg">
                        <Calendar className="w-5 h-5 mr-3"/>
                        Check Availability
                    </Button>
                </CardFooter>
             </Card>
          </div> */}
        </div>
      </div>
          {/* Footer */}
          <footer className="bg-gray-900 text-white py-12 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="grid md:grid-cols-4 gap-8 mb-8">
            <div>
              <h3 className="text-2xl font-bold text-pont-yellow mb-4">Pont Ar Gler</h3>
              <p className="text-gray-300">
                Celebrating artists and culture through unforgettable musical experiences.
              </p>
            </div>

            <div>
              <h4 className="font-bold text-lg mb-4 text-pont-green">Quick Links</h4>
              <ul className="space-y-2">
                <li>
                  <a href="#" className="text-gray-300 hover:text-pont-yellow transition-colors">
                    About
                  </a>
                </li>
                <li>
                  <a href="#" className="text-gray-300 hover:text-pont-yellow transition-colors">
                    Contact
                  </a>
                </li>
                <li>
                  <a href="#" className="text-gray-300 hover:text-pont-yellow transition-colors">
                    Artists
                  </a>
                </li>
                <li>
                  <a href="#" className="text-gray-300 hover:text-pont-yellow transition-colors">
                    Events
                  </a>
                </li>
              </ul>
            </div>

            <div>
              <h4 className="font-bold text-lg mb-4 text-pont-green">Event Types</h4>
              <ul className="space-y-2">
                <li>
                  <a href="#" className="text-gray-300 hover:text-pont-yellow transition-colors">
                    Festivals
                  </a>
                </li>
                <li>
                  <a href="#" className="text-gray-300 hover:text-pont-yellow transition-colors">
                    Concerts
                  </a>
                </li>
                <li>
                  <a href="#" className="text-gray-300 hover:text-pont-yellow transition-colors">
                    Exhibitions
                  </a>
                </li>
                <li>
                  <a href="#" className="text-gray-300 hover:text-pont-yellow transition-colors">
                    Workshops
                  </a>
                </li>
              </ul>
            </div>

            <div>
              <h4 className="font-bold text-lg mb-4 text-pont-green">Follow Us</h4>
              <div className="flex space-x-4">
                <a href="#" className="text-gray-300 hover:text-pont-yellow transition-colors">
                  <Facebook className="w-6 h-6" />
                </a>
                <a href="#" className="text-gray-300 hover:text-pont-yellow transition-colors">
                  <Instagram className="w-6 h-6" />
                </a>
                <a href="#" className="text-gray-300 hover:text-pont-yellow transition-colors">
                  <Twitter className="w-6 h-6" />
                </a>
                <a href="#" className="text-gray-300 hover:text-pont-yellow transition-colors">
                  <Mail className="w-6 h-6" />
                </a>
              </div>
            </div>
          </div>

          <div className="border-t border-gray-700 pt-8 text-center">
            <p className="text-gray-400">© {new Date().getFullYear()} Pont Ar Gler. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  )
}
